"""add_equipment_safety_escalation_incident_reports

Revision ID: 3ace5fb0bea6
Revises: 6d46e7c7dc54
Create Date: 2026-02-23 11:31:29.937063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ace5fb0bea6'
down_revision: Union[str, Sequence[str], None] = '6d46e7c7dc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('process_line', sa.String(length=32), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upstream_id', sa.String(length=32), nullable=True),
    sa.Column('downstream_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['downstream_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['upstream_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_levels',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('escalation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition', sa.String(length=128), nullable=False),
    sa.Column('confidence_min', sa.Float(), nullable=True),
    sa.Column('confidence_max', sa.Float(), nullable=True),
    sa.Column('safety_impact', sa.String(length=16), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('severity_class', sa.String(length=16), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_equipment_type'), 'safety_rules', ['equipment_type'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('process_line', sa.String(length=32), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('turning_point_signal', sa.Text(), nullable=True),
    sa.Column('decision_taken', sa.Text(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lessons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('safety_level', sa.String(length=16), nullable=True),
    sa.Column('diagnosis_time_traditional', sa.Integer(), nullable=True),
    sa.Column('diagnosis_time_structured', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_asset_id'), 'incident_reports', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_reports_asset_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_safety_rules_equipment_type'), table_name='safety_rules')
    op.drop_table('safety_rules')
    op.drop_table('escalation_rules')
    op.drop_table('escalation_levels')
    op.drop_table('equipment')
    # ### end Alembic commands ###
