"""remove slug

Revision ID: 3d867abfd16b
Revises: b1a2c3d4e5f6
Create Date: 2026-04-02 08:05:06.695482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d867abfd16b'
down_revision: Union[str, Sequence[str], None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_column('companies', 'slug')
    op.create_index(op.f('ix_equipment_downstream_id'), 'equipment', ['downstream_id'], unique=False)
    op.create_index(op.f('ix_equipment_upstream_id'), 'equipment', ['upstream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_upstream_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_downstream_id'), table_name='equipment')
    op.add_column('companies', sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###
