"""remove slug

Revision ID: 3d867abfd16b
Revises: a9b1c2d3e4f5
Create Date: 2026-04-02 08:05:06.695482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '3d867abfd16b'
down_revision: Union[str, Sequence[str], None] = 'a9b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    tables = inspector.get_table_names()
    if "companies" in tables:
        company_cols = {c["name"] for c in inspector.get_columns("companies")}
        if "slug" in company_cols:
            try:
                op.drop_index(op.f('ix_companies_slug'), table_name='companies')
            except Exception:
                pass
            op.drop_column('companies', 'slug')

    if "equipment" in tables:
        existing_indexes = {idx.get("name") for idx in inspector.get_indexes("equipment")}
        idx_down = op.f('ix_equipment_downstream_id')
        idx_up = op.f('ix_equipment_upstream_id')
        if idx_down not in existing_indexes:
            op.create_index(idx_down, 'equipment', ['downstream_id'], unique=False)
        if idx_up not in existing_indexes:
            op.create_index(idx_up, 'equipment', ['upstream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_upstream_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_downstream_id'), table_name='equipment')
    op.add_column('companies', sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###
