"""initial_schema_incidents_qa_outcomes

Revision ID: 6d46e7c7dc54
Revises: 
Create Date: 2026-02-20 15:25:10.711693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d46e7c7dc54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('normalized_summary', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('safety_level', sa.String(length=16), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('initial_risk_score', sa.Float(), nullable=True),
    sa.Column('reported_by', sa.String(length=128), nullable=True),
    sa.Column('root_cause_category', sa.String(length=32), nullable=True),
    sa.Column('process_line', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('current_diagnostic_step', sa.Integer(), nullable=True),
    sa.Column('questions_asked_count', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('memory_written', sa.Boolean(), nullable=True),
    sa.Column('verification_confirmed', sa.Boolean(), nullable=True),
    sa.Column('escalation_triggered', sa.Boolean(), nullable=True),
    sa.Column('process_failure_suspected', sa.Boolean(), nullable=True),
    sa.Column('incident_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_failure_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnosis_start_time', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_end_time', sa.String(length=64), nullable=True),
    sa.Column('mttd_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_asset_id'), 'incidents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('outcome_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('root_cause_confirmed', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=32), nullable=True),
    sa.Column('turning_point_signal', sa.Text(), nullable=True),
    sa.Column('why_previous_failed', sa.Text(), nullable=True),
    sa.Column('risk_adjustment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_records_incident_id'), 'outcome_records', ['incident_id'], unique=False)
    op.create_table('qa_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('diagnostic_step', sa.Integer(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_history_incident_id'), 'qa_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_history_incident_id'), table_name='qa_history')
    op.drop_table('qa_history')
    op.drop_index(op.f('ix_outcome_records_incident_id'), table_name='outcome_records')
    op.drop_table('outcome_records')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_asset_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
