"""Add expiry_date to Company and contact_number to User

Revision ID: 89906b40f6e2
Revises: b1a2c3d4e5f6
Create Date: 2026-04-24 15:31:24.903817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89906b40f6e2'
down_revision: Union[str, Sequence[str], None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('contact_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.drop_column('companies', 'expiry_date')
    # ### end Alembic commands ###
